sylius:
#  expression_language:
#    - 'Kiboko\Component\ArrayExpressionLanguage\ArrayExpressionLanguageProvider'
  extractor:
    type: countries
    code: '@=input["code"]'
    method: all
    search:
      - { field: enabled, operator: '=', value: '@=input["code"]', scope: '@=input["scope"]', locale: '@=input["fr_FR"]' }
  client:
    api_url: 'http://demo.akeneo.com/'
    client_id: '5_5555o1hi5vggs8k0kw8gks80wwow4ckgogok48cgc8ggsco8os'
    secret: 't04o6nh5vtw4wkcg0swocs8wcoskg0ck84sggcs4ok0oo8c8k'
    username: 'sylius_9794'
    password: 'a60d900c9'
